config/routes.rb
Rails.application.routes.draw do

  resources :agents do
    resources :contacts do
      member do
        get "sdefault", :as => "sdefault"
      end
    end
  end

  root 'agents#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :contacts
  belongs_to :contact
  accepts_nested_attributes_for :contacts
  validates :title, presence: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :agent, foreign_key: "agent_id"
  validates :email, presence: true, :email => true

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  # before_filter :find_agent
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    # @agents = Agent.all
    @agents = Agent.order(:id).page(params[:page]).per(3)
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
    @contacts = @agent.contacts

  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit(:title, :contact_id)
    end

    def find_agent
      @agent = Agent.find( params[:agent_id] )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :sdefault]
  before_filter :find_agent

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    # @contacts = @agent.contacts

  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    @agent = Agent.find(params[:agent_id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = @agent.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        if @agent.contact.nil?
          @agent.contact = @contact
          @agent.save
        end
        format.html { redirect_to agent_url(@agent), notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to agent_contact_url(@agent,@contact), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to agent_url(@agent), notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sdefault
    @agent.contact = @contact
    @agent.save
    redirect_to agent_url(@agent), notice: "Default contact is #{@contact.email}"
  end
  def find_agent
    @agent = Agent.find(params[:agent_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :agent_id)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
<!--   <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.number_field :contact_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent , :class=>"btn btn-default"%> |
<%= link_to 'Back', agents_path , :class=>"btn btn-default"%>

app/views/agents/index.html.erb
<h1>Listing Agents</h1>

<table class="table">
<%= link_to 'New Agent', new_agent_path , :class=>"btn btn-warning"%>

  <thead>
    <tr>
      <th>Title</th>
      <th>Default Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.title %></td>
        <td><%= agent.contact.email if !agent.contact.nil? %></td>
        <td><%= link_to 'Show', agent , :class=>"btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_agent_path(agent) , :class=>"btn btn-primary"%></td>
        <td><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @agents, :theme => 'twitter-bootstrap-3' %>
<br>

app/views/agents/new.html.erb
<h1>New agent</h1>

<%= render 'form' %>

<%= link_to 'Back', agents_path , :class => "btn btn-default"%>

app/views/agents/show.html.erb
  <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <h4><%= @agent.title %></h4>
</p>

<p>
  <strong>Default email:</strong>
  <%= @agent.contact.email if ! @agent.contact.nil? %>
</p>
<table class="table">
  <thead>
    <tr>
      <%= link_to 'Add email', new_agent_contact_path(@agent), :class => "btn btn-default" %> |
<%= link_to 'Edit', edit_agent_path(@agent) , :class=>"btn btn-default" %>
      <th>email</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= link_to 'Edit', edit_agent_contact_path(@agent,contact), :class=>"btn btn-primary" %></td>
        <td><%= link_to 'Set default', sdefault_agent_contact_path(@agent,contact) , :class => "btn btn-success" %></td>
        <td><%= link_to 'Destroy',agent_contact_path(@agent,contact), method: :delete , :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', agents_path , :class=>"btn btn-default" %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>
<%= form_for(@contact, :url => agent_contact_path(@agent,@contact)) do |e| %>
  <div class="field">
    <%= e.label :email %><br>
    <%= e.email_field :email %>
  </div>
  <div class="actions">
    <%= e.submit %>
  </div>
<% end %>

<%= link_to 'Back', agent_path(@agent) , :class => "btn btn-default"%>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= contact.agent_id %></td>
        <td><%= link_to 'Show', agent_contacts_path %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= form_for(@contact, :url => agent_contacts_path(@agent,@contact)) do |e| %>

  <div class="field">
    <%= e.label :email %><br>
    <%= e.email_field :email %>
  </div>
  <div class="actions">
    <%= e.submit %>
  </div>
<% end %>

<%= link_to 'Back', agent_path(@agent) , :class => "btn btn-default"%>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @contact.agent_id %>
</p>

<%= link_to 'Back', agent_path(@agent) , :class => "btn btn-default"%>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Agents List', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rentguard Bobo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rentguard Bobo" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container">

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </div>
  </body>
</html>